# Supabase local configuration for Cliply Backend
# Reference: https://supabase.com/docs/guides/local-development/cli/config

project_id = "cliply-backend"

# --- API (PostgREST) ---
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

# --- AUTH (GoTrue) ---
[auth]
enabled = true
site_url = "http://127.0.0.1:54321"
additional_redirect_urls = ["http://localhost:54321"]

# ✅ Use HS256 for local development
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters"
jwt_expiry = 3600


# --- TLS ---
[api.tls]
enabled = false
# cert_path = "../certs/my-cert.pem"
# key_path  = "../certs/my-key.pem"

# --- DATABASE ---
[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

# --- REALTIME ---
[realtime]
enabled = true

# --- STUDIO ---
[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

# --- ANALYTICS ---
[analytics]
enabled = false
