# Supabase local configuration for Cliply Backend
# Reference: https://supabase.com/docs/guides/local-development/cli/config

project_id = "cliply-backend"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:54321"
additional_redirect_urls = ["http://localhost:54321"]

# ✅ JWK for RS256 public key verification
jwt_secret = '''
{
  "kty": "RSA",
  "alg": "RS256",
  "use": "sig",
  "kid": "cliply-local",
  "n": "rh2EeUsgF_w2f4npx0bprYkMB0aV1EFUtbnVR-x3ghyv8OYdSAzKRauLvlvGVXi7tq83boAai3aYJf3TLroHdyxppmrASVO165yJWeaFuhxb8RIiTvmcPLA8vQ2l6wbK6E2y3NYagi-L6E8bZdDI_mHm-Ei2gG0L2iS-v-TkVfshRy0CKhPxszcmSeM1tQycX-am3rdtOaE3wPHk48Z2AtmJB7lLbDGo9g6U0n5i1BCsbTBBYIjRsGyeARhlEzXyOV7lP1HC7C4foCQqzDxEfexwP0T1V_nF1XP45HRT4PVTKqrPsVCza23JWHbiwr-8jHiWMn_PxNfspbb_HpR3tw",
  "e": "AQAB"
}
'''
jwt_expiry = 3600



[api.tls]
enabled = false
# cert_path = "../certs/my-cert.pem"
# key_path = "../certs/my-key.pem"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[analytics]
enabled = false
