#!/bin/bash
# Verification script for Vercel cron job setup
# Usage: ./scripts/verify-cron.sh <vercel-deployment-url>

set -e

DEPLOYMENT_URL="${1:-}"

if [ -z "$DEPLOYMENT_URL" ]; then
  echo "❌ Error: Deployment URL required"
  echo "Usage: ./scripts/verify-cron.sh https://your-app.vercel.app"
  exit 1
fi

# Remove trailing slash if present
DEPLOYMENT_URL="${DEPLOYMENT_URL%/}"

echo "🔍 Verifying Cron Setup for: $DEPLOYMENT_URL"
echo ""

# Test 1: Health check
echo "Test 1: Health Check"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$DEPLOYMENT_URL/api/health/audit")
if [ "$HTTP_CODE" -eq 200 ]; then
  echo "✅ Health endpoint reachable (200 OK)"
else
  echo "⚠️  Health endpoint returned: $HTTP_CODE"
fi
echo ""

# Test 2: Cron endpoint (should return 403 without auth)
echo "Test 2: Cron Endpoint (without auth - expecting 403)"
CRON_RESPONSE=$(curl -s -X POST "$DEPLOYMENT_URL/api/cron/scan-schedules" -w "\n%{http_code}")
HTTP_CODE=$(echo "$CRON_RESPONSE" | tail -n1)
BODY=$(echo "$CRON_RESPONSE" | head -n-1)

if [ "$HTTP_CODE" -eq 403 ]; then
  echo "✅ Cron endpoint protected (403 FORBIDDEN)"
elif [ "$HTTP_CODE" -eq 405 ]; then
  echo "⚠️  Method not allowed (use POST)"
else
  echo "⚠️  Unexpected response: $HTTP_CODE"
  echo "   Body: $BODY"
fi
echo ""

# Test 3: Cron with service role key (if provided)
if [ -n "$SUPABASE_SERVICE_ROLE_KEY" ]; then
  echo "Test 3: Cron Endpoint (with service role auth)"
  CRON_RESPONSE=$(curl -s -X POST "$DEPLOYMENT_URL/api/cron/scan-schedules" \
    -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
    -w "\n%{http_code}")
  HTTP_CODE=$(echo "$CRON_RESPONSE" | tail -n1)
  BODY=$(echo "$CRON_RESPONSE" | head -n-1)
  
  if [ "$HTTP_CODE" -eq 200 ]; then
    echo "✅ Cron endpoint authenticated successfully"
    echo "   Response: $BODY"
  else
    echo "❌ Authentication failed: $HTTP_CODE"
    echo "   Body: $BODY"
  fi
else
  echo "Test 3: Skipped (set SUPABASE_SERVICE_ROLE_KEY to test manual auth)"
fi
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 NEXT STEPS:"
echo ""
echo "1. Verify Vercel Dashboard → Settings → Environment Variables"
echo "   Required vars (Preview + Production):"
echo "   - SUPABASE_URL"
echo "   - SUPABASE_SERVICE_ROLE_KEY"
echo "   - STRIPE_SECRET_KEY"
echo "   - STRIPE_WEBHOOK_SECRET"
echo "   - SENTRY_DSN"
echo "   - TIKTOK_CLIENT_KEY"
echo "   - TIKTOK_CLIENT_SECRET"
echo "   - CRON_SECRET (auto-generated by Vercel)"
echo ""
echo "2. Check Vercel Dashboard → Cron Jobs → Logs"
echo "   Expected: Logs every 5 minutes with 200 OK status"
echo ""
echo "3. Monitor for 10-15 minutes to confirm automatic execution"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

